### ISSUE TITLE
Question on Storage

### ISSUE THREAD

**Issue by Laxshen** [Dhinessplayz/AI-spy-software#1]
how much does our storage actually have 
and how much space?

**Comment by Dhinessplayz** [comment]
The end project is expected to take around 1GB in a .exe format maybe less if we separate the AI and the spyware.

**Comment by Laxshen** [comment]
So how much storage would it take if we didn't split the package

**Comment by Dhinessplayz** [comment]
As already mentioned, if we didn't split the package, then it is expected to be around 1GB but I'm trying to get it below half of the expected limit.

**Comment by Laxshen** [comment]
ok
