### ISSUE TITLE
Keylogger issue

### ISSUE THREAD

**Issue by Laxshen** [Dhinessplayz/AI-spy-software#4]
Are You sure that the key logger from another repo works, and do we have any tests made yet.if no when?

**Comment by Dhinessplayz** [comment]
The keylogger does work to an extent, we only have a team of 4 and its really not easy to pull everything together. We are trying our best!

The issue with the keylooger lies in its last lines, off the top of my head it was something about a null value being assigned to  itself, one of my teamates is working on it as we speak
